### ISSUE TITLE
differentiate print output between DUT and TrafficGen

### ISSUE THREAD

**Issue by jianzzha** [redhat-partner-solutions/intel-sriov-test#47]
currently on html stdout output can't tell which commands is from DUT which is from TrafficGen

**Comment by dkosteck** [comment]
Done via https://github.com/redhat-partner-solutions/intel-sriov-test/commit/56f1505a328fb6544b74f3e0e94fcef56ce538fd

Will close when merged into main

**Comment by dkosteck** [comment]
Done via #79
